
server:
  port: 8081

spring:
  application:
    name: microservice-a

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      myCircuitBreaker:
        failure-rate-threshold: 50
        sliding-window-size: 5
