
server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: microservice-route
          uri: lb://microservice-a
          predicates:
            - Path=/api/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
